using System.Collections;
using System.IO;
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Linq;

namespace LeetCodeNote
{
    class Program
    {
        static void Main(string[] args)
        {
            int[] nums = {3,2,6,5,0,3};
            int k = 4;
            int n = 13;
            int m = 2;
            int[] group = {-1,-1,1,0,0,1,0,-1};
            int[][] edges = new int[][]{
                new int[]{1,1,2},
                new int[]{2,1,3},
                new int[]{3,2,4},
                new int[]{3,2,5},
                new int[]{1,2,6},
                new int[]{3,6,7},
                new int[]{3,7,8},
                new int[]{3,6,9},
                new int[]{3,4,10},
                new int[]{2,3,11},
                new int[]{1,5,12},
                new int[]{3,3,13},
                new int[]{2,1,10},
                new int[]{2,6,11},
                new int[]{3,5,13},
                new int[]{1,9,12},
                new int[]{1,6,8},
                new int[]{3,6,13},
                new int[]{2,1,4},
                new int[]{1,1,13},
                new int[]{2,9,10},
                new int[]{2,1,6},
                new int[]{2,10,13},
                new int[]{2,2,9},
                new int[]{3,4,12},
                new int[]{2,4,7},
                new int[]{1,1,10},
                new int[]{1,3,7},
                new int[]{1,7,11},
                new int[]{3,3,12},
                new int[]{2,4,8},
                new int[]{3,8,9},
                new int[]{1,9,13},
                new int[]{2,4,10},
                new int[]{1,6,9},
                new int[]{3,10,13},
                new int[]{1,7,10},
                new int[]{1,1,11},
                new int[]{2,4,9},
                new int[]{3,5,11},
                new int[]{3,2,6},
                new int[]{2,1,5},
                new int[]{2,5,11},
                new int[]{2,1,7},
                new int[]{2,3,8},
                new int[]{2,8,9},
                new int[]{3,4,13},
                new int[]{3,3,8},
                new int[]{3,3,11},
                new int[]{2,9,11},
                new int[]{3,1,8},
                new int[]{2,1,8},
                new int[]{3,8,13},
                new int[]{2,10,11},
                new int[]{3,1,5},
                new int[]{1,10,11},
                new int[]{1,7,12},
                new int[]{2,3,5},
                new int[]{3,1,13},
                new int[]{2,4,11},
                new int[]{2,3,9},
                new int[]{2,6,9},
                new int[]{2,1,13},
                new int[]{3,1,12},
                new int[]{2,7,8},
                new int[]{2,5,6},
                new int[]{3,1,9},
                new int[]{1,5,10},
                new int[]{3,2,13},
                new int[]{2,3,6},
                new int[]{2,2,10},
                new int[]{3,4,11},
                new int[]{1,4,13},
                new int[]{3,5,10},
                new int[]{1,4,10},
                new int[]{1,1,8},
                new int[]{3,3,4},
                new int[]{2,4,6},
                new int[]{2,7,11},
                new int[]{2,7,10},
                new int[]{2,3,12},
                new int[]{3,7,11},
                new int[]{3,9,10},
                new int[]{2,11,13},
                new int[]{1,1,12},
                new int[]{2,10,12},
                new int[]{1,7,13},
                new int[]{1,4,11},
                new int[]{2,4,5},
                new int[]{1,3,10},
                new int[]{2,12,13},
                new int[]{3,3,10},
                new int[]{1,6,12},
                new int[]{3,6,10},
                new int[]{1,3,4},
                new int[]{2,7,9},
                new int[]{1,3,11},
                new int[]{2,2,8},
                new int[]{1,2,8},
                new int[]{1,11,13},
                new int[]{1,2,13},
                new int[]{2,2,6},
                new int[]{1,4,6},
                new int[]{1,6,11},
                new int[]{3,1,2},
                new int[]{1,1,3},
                new int[]{2,11,12},
                new int[]{3,2,11},
                new int[]{1,9,10},
                new int[]{2,6,12},
                new int[]{3,1,7},
                new int[]{1,4,9},
                new int[]{1,10,12},
                new int[]{2,6,13},
                new int[]{2,2,12},
                new int[]{2,1,11},
                new int[]{2,5,9},
                new int[]{1,3,8},
                new int[]{1,7,8},
                new int[]{1,2,12},
                new int[]{1,5,11},
                new int[]{2,7,12},
                new int[]{3,1,11},
                new int[]{3,9,12},
                new int[]{3,2,9},
                new int[]{3,10,11}
            };

            var result = Solution1579.MaxNumEdgesToRemove(n, edges);

            Console.WriteLine(result);
            Console.WriteLine("Hello World!");
        }
    }
}
